// Package proto holds the wire-format schema and generated code for the
// sentinel transport (DECISION D27).
//
// The schema is the source of truth for the on-wire protocol; the generated
// .pb.go file is committed to the repo so a clean checkout builds without
// protoc. Regeneration is via `go generate ./pkg/transport/...` (see
// protocol.go's //go:generate directive) or directly with protoc against this
// file.
//
// Versioning: every Frame carries protocol_version. v0.1.0 frames use
// protocol_version = 1. A node that receives an unsupported version drops
// the frame and logs at WARN (D27 §3). The wire format itself is closed for
// v0.1.0 (D29): adding message types requires a flow and a protocol_version
// bump, not a silent schema edit.
//
// Message types are grouped by their natural stream (D27 §2):
//   - Telemetry stream (uni, high-frequency, fire-and-forget): Heartbeat,
//     TelemetryBatch, Alert.
//   - Control stream (bi, request/response, low-frequency, ordered): Ping,
//     Pong, RuleUpdate, RuleUpdateAck.
//
// "IANA: user-agent" for the wire format is intentionally not declared —
// v0.1.0 is an internal sentinel-to-sentinel protocol with no IANA
// registration. Field numbers are part of the on-wire contract and must not
// be reshuffled without a version bump.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: transport.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricType identifies how a MetricSample.value should be interpreted.
type MetricType int32

const (
	MetricType_COUNTER_UNSPECIFIED MetricType = 0 // proto3 default; same wire as COUNTER.
	MetricType_COUNTER             MetricType = 1 // Monotonically increasing cumulative value.
	MetricType_GAUGE               MetricType = 2 // Point-in-time snapshot.
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0: "COUNTER_UNSPECIFIED",
		1: "COUNTER",
		2: "GAUGE",
	}
	MetricType_value = map[string]int32{
		"COUNTER_UNSPECIFIED": 0,
		"COUNTER":             1,
		"GAUGE":               2,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

// AlertSeverity is the alert's severity bucket. v0.1.0 ships a small,
// stable set; future versions may add levels without a version bump
// (proto3 enums are forward-compatible).
type AlertSeverity int32

const (
	AlertSeverity_INFO_UNSPECIFIED AlertSeverity = 0 // proto3 default; same wire as INFO.
	AlertSeverity_INFO             AlertSeverity = 1
	AlertSeverity_WARNING          AlertSeverity = 2
	AlertSeverity_CRITICAL         AlertSeverity = 3
)

// Enum value maps for AlertSeverity.
var (
	AlertSeverity_name = map[int32]string{
		0: "INFO_UNSPECIFIED",
		1: "INFO",
		2: "WARNING",
		3: "CRITICAL",
	}
	AlertSeverity_value = map[string]int32{
		"INFO_UNSPECIFIED": 0,
		"INFO":             1,
		"WARNING":          2,
		"CRITICAL":         3,
	}
)

func (x AlertSeverity) Enum() *AlertSeverity {
	p := new(AlertSeverity)
	*p = x
	return p
}

func (x AlertSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[1].Descriptor()
}

func (AlertSeverity) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[1]
}

func (x AlertSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertSeverity.Descriptor instead.
func (AlertSeverity) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

// AckStatus is the outcome of a RuleUpdate.
type AckStatus int32

const (
	AckStatus_APPLIED_UNSPECIFIED AckStatus = 0 // proto3 default; same wire as APPLIED.
	AckStatus_APPLIED             AckStatus = 1 // Rule was successfully applied.
	AckStatus_REJECTED            AckStatus = 2 // Rule was rejected; see RuleUpdateAck.reason.
)

// Enum value maps for AckStatus.
var (
	AckStatus_name = map[int32]string{
		0: "APPLIED_UNSPECIFIED",
		1: "APPLIED",
		2: "REJECTED",
	}
	AckStatus_value = map[string]int32{
		"APPLIED_UNSPECIFIED": 0,
		"APPLIED":             1,
		"REJECTED":            2,
	}
)

func (x AckStatus) Enum() *AckStatus {
	p := new(AckStatus)
	*p = x
	return p
}

func (x AckStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AckStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_transport_proto_enumTypes[2].Descriptor()
}

func (AckStatus) Type() protoreflect.EnumType {
	return &file_transport_proto_enumTypes[2]
}

func (x AckStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AckStatus.Descriptor instead.
func (AckStatus) EnumDescriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

// Frame is the top-level on-wire envelope sent over both telemetry and
// control streams.
//
// Every Frame carries a protocol_version so a future node can drop unknown
// versions cleanly. The body is a oneof: a Frame holds exactly ONE message
// at a time. The protobuf encoding of a oneof is a tag-pointer (NOT a
// fixed tag space) so adding a new variant in a future protocol_version is
// non-breaking on the encode side — receivers of an older version will see
// an unknown field-number and fall through to the drop-on-mismatch path
// (D27 §3).
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// protocol_version is 1 for v0.1.0. Bumped when a new variant is added
	// to Frame.body or when an existing message's semantics change.
	// Field 1 is RESERVED FOR protocol_version in every future version.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// body holds the per-message payload. Exactly one field is set.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Heartbeat
	//	*Frame_TelemetryBatch
	//	*Frame_Alert
	//	*Frame_Ping
	//	*Frame_Pong
	//	*Frame_RuleUpdate
	//	*Frame_RuleUpdateAck
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Frame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Frame) GetTelemetryBatch() *TelemetryBatch {
	if x != nil {
		if x, ok := x.Body.(*Frame_TelemetryBatch); ok {
			return x.TelemetryBatch
		}
	}
	return nil
}

func (x *Frame) GetAlert() *Alert {
	if x != nil {
		if x, ok := x.Body.(*Frame_Alert); ok {
			return x.Alert
		}
	}
	return nil
}

func (x *Frame) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Body.(*Frame_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Frame) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Body.(*Frame_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Frame) GetRuleUpdate() *RuleUpdate {
	if x != nil {
		if x, ok := x.Body.(*Frame_RuleUpdate); ok {
			return x.RuleUpdate
		}
	}
	return nil
}

func (x *Frame) GetRuleUpdateAck() *RuleUpdateAck {
	if x != nil {
		if x, ok := x.Body.(*Frame_RuleUpdateAck); ok {
			return x.RuleUpdateAck
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,10,opt,name=heartbeat,proto3,oneof"`
}

type Frame_TelemetryBatch struct {
	TelemetryBatch *TelemetryBatch `protobuf:"bytes,11,opt,name=telemetry_batch,json=telemetryBatch,proto3,oneof"`
}

type Frame_Alert struct {
	Alert *Alert `protobuf:"bytes,12,opt,name=alert,proto3,oneof"`
}

type Frame_Ping struct {
	Ping *Ping `protobuf:"bytes,20,opt,name=ping,proto3,oneof"`
}

type Frame_Pong struct {
	Pong *Pong `protobuf:"bytes,21,opt,name=pong,proto3,oneof"`
}

type Frame_RuleUpdate struct {
	RuleUpdate *RuleUpdate `protobuf:"bytes,22,opt,name=rule_update,json=ruleUpdate,proto3,oneof"`
}

type Frame_RuleUpdateAck struct {
	RuleUpdateAck *RuleUpdateAck `protobuf:"bytes,23,opt,name=rule_update_ack,json=ruleUpdateAck,proto3,oneof"`
}

func (*Frame_Heartbeat) isFrame_Body() {}

func (*Frame_TelemetryBatch) isFrame_Body() {}

func (*Frame_Alert) isFrame_Body() {}

func (*Frame_Ping) isFrame_Body() {}

func (*Frame_Pong) isFrame_Body() {}

func (*Frame_RuleUpdate) isFrame_Body() {}

func (*Frame_RuleUpdateAck) isFrame_Body() {}

// Heartbeat is a periodic liveness beacon sent on a unidirectional telemetry
// stream.
//
// Rationale: the smallest possible telemetry primitive — "this node is
// alive and running this protocol_version". Operators read heartbeat gaps
// to spot dead peers. Frequencies are NOT encoded in the message (a peer
// sends a heartbeat every N seconds; N is an operator concern, not a wire
// concern — D25).
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_node_id is the sending node's identity fingerprint, in the
	// "sha256:<hex>" form used everywhere in the transport (D23, D24). The
	// receiver does not need to trust it — the TLS handshake already pinned
	// the peer's identity — but carrying it lets operators grep logs and
	// correlate frames to nodes without re-deriving the fingerprint from the
	// QUIC connection.
	SenderNodeId string `protobuf:"bytes,1,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	// monotonic_clock_ms is the sender's monotonic clock at send time, in
	// milliseconds. The receiver does NOT interpret this as wall-clock time;
	// it is purely a delta measurement aid (heartbeat age = now - this).
	// Monotonic, not time.Now(), because wall clocks can jump backwards and
	// make the heartbeat-age math lie.
	MonotonicClockMs uint64 `protobuf:"varint,2,opt,name=monotonic_clock_ms,json=monotonicClockMs,proto3" json:"monotonic_clock_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *Heartbeat) GetMonotonicClockMs() uint64 {
	if x != nil {
		return x.MonotonicClockMs
	}
	return 0
}

// TelemetryBatch is a single frame carrying N metric samples.
//
// Rationale: Heartbeat is "alive"; TelemetryBatch is "doing well". A single
// per-second batch is dramatically cheaper on the wire than N separate
// frames (one Protobuf envelope, one UDP datagram, one TLS record), and
// sentinel nodes generate a small fixed set of metrics (counters for
// rules evaluated, alerts emitted, etc.) at a steady rate.
//
// Each sample is a tagged (name, type, value) triple. v0.1.0 supports
// counter and gauge; other metric types (histogram, summary) are
// deferred — adding a new MetricType enum value is a non-breaking change
// in proto3 (unknown enum values are dropped, not rejected), so a future
// version can extend the set without a version bump.
type TelemetryBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_node_id follows the same convention as Heartbeat.
	SenderNodeId string `protobuf:"bytes,1,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	// monotonic_clock_ms is the batch's send-time, in the same convention
	// as Heartbeat.
	MonotonicClockMs uint64 `protobuf:"varint,2,opt,name=monotonic_clock_ms,json=monotonicClockMs,proto3" json:"monotonic_clock_ms,omitempty"`
	// samples are the per-metric values in this batch. A batch MAY be empty
	// (no samples) — that is a legal "nothing to report" frame.
	Samples       []*MetricSample `protobuf:"bytes,3,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryBatch) Reset() {
	*x = TelemetryBatch{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryBatch) ProtoMessage() {}

func (x *TelemetryBatch) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryBatch.ProtoReflect.Descriptor instead.
func (*TelemetryBatch) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetryBatch) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *TelemetryBatch) GetMonotonicClockMs() uint64 {
	if x != nil {
		return x.MonotonicClockMs
	}
	return 0
}

func (x *TelemetryBatch) GetSamples() []*MetricSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

// MetricSample is one name + typed value pair inside a TelemetryBatch.
type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the metric name. v0.1.0 names are operator-defined strings;
	// the transport does not interpret them. A future version may declare
	// a canonical name registry.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type selects the interpretation of value. Unknown types at the
	// receiver are dropped (per proto3 enum rules) without rejecting the
	// whole batch.
	Type MetricType `protobuf:"varint,2,opt,name=type,proto3,enum=arx.transport.v1.MetricType" json:"type,omitempty"`
	// value is the metric's value. Interpretation depends on type:
	//
	//	COUNTER_UNSPECIFIED / GAUGE: the integer reading at sample time.
	//
	// The unit is metric-name-defined (operators agree on "rules_evaluated"
	// being a count, "cpu_usage_pct" being a percentage). The wire format
	// does not carry units.
	Value         uint64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *MetricSample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSample) GetType() MetricType {
	if x != nil {
		return x.Type
	}
	return MetricType_COUNTER_UNSPECIFIED
}

func (x *MetricSample) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Alert is a security event forwarded from a leaf node to a coordinator
// or hub (D25: hub-spoke and hierarchical topologies are first-class).
//
// Rationale: the sentinel product's reason for existing is to detect and
// surface events. The transport MUST carry alerts even in v0.1.0;
// deferring this to a later flow would make the transport package
// structurally incomplete (it could move bytes but not the actual
// product payload). The alert is sent on a telemetry stream (uni,
// fire-and-forget) — alerts are not acknowledged at the transport level
// in v0.1.0; dedup / ack is a higher-level concern.
//
// The rule_id and severity fields let the receiver route the alert
// without inspecting payload bytes. payload is opaque to the transport
// and is the arxsentinel product's responsibility to format (D30: alert
// schema is product-side, not arx-core).
type Alert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_node_id follows the same convention as Heartbeat.
	SenderNodeId string `protobuf:"bytes,1,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	// monotonic_clock_ms is the alert's send-time.
	MonotonicClockMs uint64 `protobuf:"varint,2,opt,name=monotonic_clock_ms,json=monotonicClockMs,proto3" json:"monotonic_clock_ms,omitempty"`
	// rule_id identifies which rule fired. v0.1.0 carries the raw ID
	// string; a future version may declare a typed ID.
	RuleId string `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// severity is the alert's severity. proto3 enum rules apply: unknown
	// values are dropped at the receiver without rejecting the frame.
	Severity AlertSeverity `protobuf:"varint,4,opt,name=severity,proto3,enum=arx.transport.v1.AlertSeverity" json:"severity,omitempty"`
	// payload is the alert's body, opaque to the transport layer. The
	// arxsentinel product defines the encoding; arx-core does not parse it.
	Payload       []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *Alert) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *Alert) GetMonotonicClockMs() uint64 {
	if x != nil {
		return x.MonotonicClockMs
	}
	return 0
}

func (x *Alert) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *Alert) GetSeverity() AlertSeverity {
	if x != nil {
		return x.Severity
	}
	return AlertSeverity_INFO_UNSPECIFIED
}

func (x *Alert) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Ping is a liveness probe sent from one peer to another on a
// bidirectional control stream. The receiver MUST answer with a Pong
// carrying the same nonce.
//
// Rationale: Heartbeat is asynchronous, uni-directional, and
// "best-effort" (a dropped heartbeat looks like a slow peer). Ping/Pong
// is synchronous, request/response, and gives the sender a concrete
// round-trip-time measurement for diagnostics ("operator runs ping, gets
// back 42ms, knows the link is healthy"). It uses a different stream
// type (control, not telemetry) because control streams are ordered and
// loss-recovered by QUIC — telemetry streams are not.
//
// nonce is a random 8-byte value chosen by the sender. The receiver
// echoes it back in Pong so the sender can match requests to responses
// (a peer may have multiple in-flight pings).
type Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nonce is a sender-chosen random identifier for matching the Pong.
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// monotonic_clock_ms is the sender's monotonic clock at send time.
	MonotonicClockMs uint64 `protobuf:"varint,2,opt,name=monotonic_clock_ms,json=monotonicClockMs,proto3" json:"monotonic_clock_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *Ping) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Ping) GetMonotonicClockMs() uint64 {
	if x != nil {
		return x.MonotonicClockMs
	}
	return 0
}

// Pong is the response to a Ping. The nonce MUST equal the Ping's nonce.
//
// Rationale: see Ping. Pong carries the original nonce plus the
// receiver's clock so the sender can compute the round-trip time:
//
//	rtt_ms = receiver_monotonic_clock_ms - sender_monotonic_clock_ms.
//
// monotonic_clock values are NOT comparable across nodes (each node's
// monotonic clock starts at boot, not at epoch). The sender uses the
// value in Ping (own clock) and the value in Pong (peer's clock) to
// derive rtt — see PROTOCOL.md for the full timing math.
type Pong struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// nonce is the Ping's nonce, echoed.
	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// receiver_monotonic_clock_ms is the receiver's monotonic clock at
	// Pong send time. See Pong.rationale for the rtt derivation.
	ReceiverMonotonicClockMs uint64 `protobuf:"varint,2,opt,name=receiver_monotonic_clock_ms,json=receiverMonotonicClockMs,proto3" json:"receiver_monotonic_clock_ms,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *Pong) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Pong) GetReceiverMonotonicClockMs() uint64 {
	if x != nil {
		return x.ReceiverMonotonicClockMs
	}
	return 0
}

// RuleUpdate is a control-stream message that asks the receiver to apply
// a new or modified rule.
//
// Rationale: "control" in the transport's name means coordinated
// behaviour across the mesh. The single control-plane primitive in
// v0.1.0 is rule distribution — a coordinator publishes a rule change,
// followers apply it. There is no in-band revoke in v0.1.0 (D24: rule
// lifecycle is product-side, not transport-side); a future version can
// add RuleRevoke as a new Frame.body variant without breaking v0.1.0
// decoders.
//
// sender_node_id lets the receiver log who published the change.
// payload carries the rule definition. v0.1.0 does NOT define a rule
// schema on the wire — payload is opaque to the transport and is the
// arxsentinel product's concern (D30: rules are product-side). The
// transport only guarantees: this message was sent by a peer that
// completed the TOFU handshake.
type RuleUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sender_node_id follows the same convention as Heartbeat.
	SenderNodeId string `protobuf:"bytes,1,opt,name=sender_node_id,json=senderNodeId,proto3" json:"sender_node_id,omitempty"`
	// rule_id identifies which rule this update targets. v0.1.0 carries
	// the raw ID; a future version may declare a typed ID.
	RuleId string `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// payload is the new rule definition, opaque to the transport layer.
	// The arxsentinel product defines the encoding.
	Payload       []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdate) Reset() {
	*x = RuleUpdate{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdate) ProtoMessage() {}

func (x *RuleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdate.ProtoReflect.Descriptor instead.
func (*RuleUpdate) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *RuleUpdate) GetSenderNodeId() string {
	if x != nil {
		return x.SenderNodeId
	}
	return ""
}

func (x *RuleUpdate) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleUpdate) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RuleUpdateAck is the receiver's confirmation that a RuleUpdate was
// applied (or rejected, with a reason).
//
// Rationale: without an ack, the rule publisher cannot distinguish
// "delivered but not yet applied" from "delivered and applied" from
// "never delivered". A coordinator that re-publishes a rule without an
// ack ends up either spamming followers (no ack → republish loop) or
// never noticing a rule was rejected (no failure signal). The ack
// closes the loop at the transport level; the product layer above
// decides what to do with a rejected ack.
//
// status discriminates success/failure and carries a reason on failure.
// The receiver MUST send exactly one Ack per accepted RuleUpdate.
type RuleUpdateAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// rule_id identifies which RuleUpdate this ack corresponds to.
	RuleId string `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	// status is the application outcome. Unknown statuses are dropped at
	// the receiver without rejecting the frame (proto3 enum rule).
	Status AckStatus `protobuf:"varint,2,opt,name=status,proto3,enum=arx.transport.v1.AckStatus" json:"status,omitempty"`
	// reason is a free-form human-readable explanation. Set on REJECTED;
	// empty on APPLIED. The transport does not interpret this field.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleUpdateAck) Reset() {
	*x = RuleUpdateAck{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleUpdateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleUpdateAck) ProtoMessage() {}

func (x *RuleUpdateAck) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleUpdateAck.ProtoReflect.Descriptor instead.
func (*RuleUpdateAck) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *RuleUpdateAck) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleUpdateAck) GetStatus() AckStatus {
	if x != nil {
		return x.Status
	}
	return AckStatus_APPLIED_UNSPECIFIED
}

func (x *RuleUpdateAck) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\x10arx.transport.v1\"\xdd\x03\n" +
	"\x05Frame\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12;\n" +
	"\theartbeat\x18\n" +
	" \x01(\v2\x1b.arx.transport.v1.HeartbeatH\x00R\theartbeat\x12K\n" +
	"\x0ftelemetry_batch\x18\v \x01(\v2 .arx.transport.v1.TelemetryBatchH\x00R\x0etelemetryBatch\x12/\n" +
	"\x05alert\x18\f \x01(\v2\x17.arx.transport.v1.AlertH\x00R\x05alert\x12,\n" +
	"\x04ping\x18\x14 \x01(\v2\x16.arx.transport.v1.PingH\x00R\x04ping\x12,\n" +
	"\x04pong\x18\x15 \x01(\v2\x16.arx.transport.v1.PongH\x00R\x04pong\x12?\n" +
	"\vrule_update\x18\x16 \x01(\v2\x1c.arx.transport.v1.RuleUpdateH\x00R\n" +
	"ruleUpdate\x12I\n" +
	"\x0frule_update_ack\x18\x17 \x01(\v2\x1f.arx.transport.v1.RuleUpdateAckH\x00R\rruleUpdateAckB\x06\n" +
	"\x04body\"_\n" +
	"\tHeartbeat\x12$\n" +
	"\x0esender_node_id\x18\x01 \x01(\tR\fsenderNodeId\x12,\n" +
	"\x12monotonic_clock_ms\x18\x02 \x01(\x04R\x10monotonicClockMs\"\x9e\x01\n" +
	"\x0eTelemetryBatch\x12$\n" +
	"\x0esender_node_id\x18\x01 \x01(\tR\fsenderNodeId\x12,\n" +
	"\x12monotonic_clock_ms\x18\x02 \x01(\x04R\x10monotonicClockMs\x128\n" +
	"\asamples\x18\x03 \x03(\v2\x1e.arx.transport.v1.MetricSampleR\asamples\"j\n" +
	"\fMetricSample\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.arx.transport.v1.MetricTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x04R\x05value\"\xcb\x01\n" +
	"\x05Alert\x12$\n" +
	"\x0esender_node_id\x18\x01 \x01(\tR\fsenderNodeId\x12,\n" +
	"\x12monotonic_clock_ms\x18\x02 \x01(\x04R\x10monotonicClockMs\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\tR\x06ruleId\x12;\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x1f.arx.transport.v1.AlertSeverityR\bseverity\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"J\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12,\n" +
	"\x12monotonic_clock_ms\x18\x02 \x01(\x04R\x10monotonicClockMs\"[\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12=\n" +
	"\x1breceiver_monotonic_clock_ms\x18\x02 \x01(\x04R\x18receiverMonotonicClockMs\"e\n" +
	"\n" +
	"RuleUpdate\x12$\n" +
	"\x0esender_node_id\x18\x01 \x01(\tR\fsenderNodeId\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"u\n" +
	"\rRuleUpdateAck\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.arx.transport.v1.AckStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*=\n" +
	"\n" +
	"MetricType\x12\x17\n" +
	"\x13COUNTER_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCOUNTER\x10\x01\x12\t\n" +
	"\x05GAUGE\x10\x02*J\n" +
	"\rAlertSeverity\x12\x14\n" +
	"\x10INFO_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\f\n" +
	"\bCRITICAL\x10\x03*?\n" +
	"\tAckStatus\x12\x17\n" +
	"\x13APPLIED_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aAPPLIED\x10\x01\x12\f\n" +
	"\bREJECTED\x10\x02B3Z1github.com/mr-addams/arx-core/pkg/transport/protob\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_transport_proto_goTypes = []any{
	(MetricType)(0),        // 0: arx.transport.v1.MetricType
	(AlertSeverity)(0),     // 1: arx.transport.v1.AlertSeverity
	(AckStatus)(0),         // 2: arx.transport.v1.AckStatus
	(*Frame)(nil),          // 3: arx.transport.v1.Frame
	(*Heartbeat)(nil),      // 4: arx.transport.v1.Heartbeat
	(*TelemetryBatch)(nil), // 5: arx.transport.v1.TelemetryBatch
	(*MetricSample)(nil),   // 6: arx.transport.v1.MetricSample
	(*Alert)(nil),          // 7: arx.transport.v1.Alert
	(*Ping)(nil),           // 8: arx.transport.v1.Ping
	(*Pong)(nil),           // 9: arx.transport.v1.Pong
	(*RuleUpdate)(nil),     // 10: arx.transport.v1.RuleUpdate
	(*RuleUpdateAck)(nil),  // 11: arx.transport.v1.RuleUpdateAck
}
var file_transport_proto_depIdxs = []int32{
	4,  // 0: arx.transport.v1.Frame.heartbeat:type_name -> arx.transport.v1.Heartbeat
	5,  // 1: arx.transport.v1.Frame.telemetry_batch:type_name -> arx.transport.v1.TelemetryBatch
	7,  // 2: arx.transport.v1.Frame.alert:type_name -> arx.transport.v1.Alert
	8,  // 3: arx.transport.v1.Frame.ping:type_name -> arx.transport.v1.Ping
	9,  // 4: arx.transport.v1.Frame.pong:type_name -> arx.transport.v1.Pong
	10, // 5: arx.transport.v1.Frame.rule_update:type_name -> arx.transport.v1.RuleUpdate
	11, // 6: arx.transport.v1.Frame.rule_update_ack:type_name -> arx.transport.v1.RuleUpdateAck
	6,  // 7: arx.transport.v1.TelemetryBatch.samples:type_name -> arx.transport.v1.MetricSample
	0,  // 8: arx.transport.v1.MetricSample.type:type_name -> arx.transport.v1.MetricType
	1,  // 9: arx.transport.v1.Alert.severity:type_name -> arx.transport.v1.AlertSeverity
	2,  // 10: arx.transport.v1.RuleUpdateAck.status:type_name -> arx.transport.v1.AckStatus
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	file_transport_proto_msgTypes[0].OneofWrappers = []any{
		(*Frame_Heartbeat)(nil),
		(*Frame_TelemetryBatch)(nil),
		(*Frame_Alert)(nil),
		(*Frame_Ping)(nil),
		(*Frame_Pong)(nil),
		(*Frame_RuleUpdate)(nil),
		(*Frame_RuleUpdateAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		EnumInfos:         file_transport_proto_enumTypes,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
